REM   Script: Session 01
REM   My SQL Project

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from olym;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM_ATHLETES;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|----- this shows us the athlete names and gender.  Now to see if it matches with  


select * from OLYM.OLYM_ATHLETE_GAMES;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|----- this shows us the athlete names and gender.  Now to see if it matches with  


select * from OLYM.OLYM_ATHLETE_GAMES;

|---- Now I need to find values for Game ID and Nation ID in order to find out how many Italians were here in 2012 


select * from OLYM.OLYM_NATIONS return 10;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|----- this shows us the athlete names and gender.  Now to see if it matches with  


select * from OLYM.OLYM_ATHLETE_GAMES;

|---- Now I need to find values for Game ID and Nation ID in order to find out how many Italians were here in 2012 


select * from OLYM.OLYM_NATIONS Limit 10;

select * from OLYM.OLYM_NATIONS limit 10;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|----- this shows us the athlete names and gender.  Now to see if it matches with  


select * from OLYM.OLYM_ATHLETE_GAMES;

|---- Now I need to find values for Game ID and Nation ID in order to find out how many Italians were here in 2012 


select * from OLYM.OLYM_NATIONS  
limit 10;

|---- SQL Project: Bootcamp: 


|----- Step 1: Querying the database to to find how many athletes were from Italy 


select * from OLYM.OLYM_ATHLETES;

|----- this shows us the athlete names and gender.  Now to see if it matches with  


select * from OLYM.OLYM_ATHLETE_GAMES;

|---- Now I need to find values for Game ID and Nation ID in order to find out how many Italians were here in 2012 


select * from OLYM.OLYM_NATIONS  
FIRST 3 ROWS ONLY;

select * from OLYM.OLYM_NATIONS  
FIRST 3 ROWS ONLY;

select * from OLYM.OLYM_NATIONS  
FETCH FIRST 3 ROWS ONLY;

SELECT OLYM.OLYM_ATHLETES.ID, OLYM.OLYM_ATHLETE_GAMES.NATION_ID, OLYM.OLYM_DISCIPLINES;

SELECT OLYM.OLYM_ATHLETES.ID, OLYM.OLYM_ATHLETE_GAMES.NATION_ID, OLYM.OLYM_DISCIPLINES 
FROm ((OLYM.OLYM_ATHLETES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETES.ID = OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
INNER JOIN OLYM.OLYM_NATIONS On OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID;

SELECT OLYM.OLYM_ATHLETES.ID, OLYM.OLYM_ATHLETE_GAMES.NATION_ID, OLYM.OLYM_DISCIPLINES 
FROm ((OLYM.OLYM_ATHLETES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETES.ID = OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
INNER JOIN OLYM.OLYM_NATIONS On OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_ATHLETES.ID, OLYM.OLYM_ATHLETE_GAMES.NATION_ID, OLYM.OLYM_NATIONS.ID 
FROm ((OLYM.OLYM_ATHLETES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETES.ID = OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
INNER JOIN OLYM.OLYM_NATIONS On OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_ATHLETES.ATHLETE_NAME, OLYM.OLYM_ATHLETE_GAMES.GAME_ID, OLYM.OLYM_NATIONS.NATION 
FROm ((OLYM.OLYM_ATHLETES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETES.ID = OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
INNER JOIN OLYM.OLYM_NATIONS On OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

select * from OLYM.ATHLETE_NAME 
FETCH FIRST 3 ROWS ONLY;

select * from OLYM.OLYM_MEDALS_VIEW 
FETCH FIRST 3 ROWS ONLY;

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM_ATHLETE_GAMES ON OLYM_ATHLETE_GAMES.NATION_ID =  OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID =  OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_ATHLETES.ATHLETE_NAME, OLYM.OLYM_ATHLETE_GAMES.GAME_ID, OLYM.OLYM_NATIONS.NATION 
FROm ((OLYM.OLYM_ATHLETES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETES.ID = OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
INNER JOIN OLYM.OLYM_NATIONS On OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
WHERE 
OLYM.OLYM_GAMES.YEAR=2012 
AND OLYM.OLYM_GAMES.CITY='London' 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
WHERE 
OLYM.OLYM_GAMES.YEAR=2012 ;

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID);

Where 


OLYM.OLYM_GAMES.YEAR=2008 


AND OLYM.OLYM_NATIONS.NATION = 'ITA';


SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR=2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR>2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR=2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

SELECT count (OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR=2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

SELECT OLYM.OLYM_GAMES.YEAR, OLYM.OLYM_GAMES.CITY, OLYM.OLYM_NATIONS.NATION, OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR=2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

select * from OLYM.OLYM_MEDALS_VIEW 
Where NOC='ITA';

select * from OLYM.OLYM_MEDALS_VIEW 
Where NOC='ITA' 
AND where event like 'arch%';

select * from OLYM.OLYM_MEDALS_VIEW 
Where NOC='ITA' 
AND  event like 'arch%';

SELECT count (OLYM.OLYM_ATHLETE_GAMES.ATHLETE_ID) 
FROM((OLYM.OLYM_GAMES 
INNER JOIN OLYM.OLYM_ATHLETE_GAMES ON OLYM.OLYM_GAMES.ID = OLYM.OLYM_ATHLETE_GAMES.GAME_ID) 
INNER JOIN OLYM.OLYM_NATIONS ON OLYM.OLYM_ATHLETE_GAMES.NATION_ID = OLYM.OLYM_NATIONS.ID) 
Where 
OLYM.OLYM_GAMES.YEAR=2008 
AND OLYM.OLYM_NATIONS.NATION = 'ITA';

